trainingInput:
  hyperparameters:
    goal: MINIMIZE
    hyperparameterMetricTag: loss
    maxTrials: 4
    maxParallelTrials: 4
    enableTrialEarlyStopping: True
    params:
    - parameterName: hidden_units
      type: CATEGORICAL
      categoricalValues:
      - '[128, 64, 32]'
      - '[64, 32, 16]'
      - '[32, 16]'
      - '[16, 4]'