trainingInput:
  hyperparameters:
    goal: MINIMIZE
    hyperparameterMetricTag: loss
    maxTrials: 4
    maxParallelTrials: 2
    enableTrialEarlyStopping: True
    params:
    - parameterName: hidden_units
      type: CATEGORICAL
      categoricalValues:
      - '[32, 16]'
      - '[64, 16]'
      - '[32, 8]'
      - '[64, 8]'